### ISSUE TITLE
[BUG] Parsing table codes is not supported

### ISSUE THREAD

**Issue by jitcor** [github/jekyll-commonmark-ghpages#39]
example:
```
|   Android Studio   | Gradle | Android Gradle Plugin |
| :----------------: | :----: | :-------------------: |
| Jellyfish 2023.3.1 |  8.6   |         8.4.0         |
|       4.1.2        |  6.5   |         4.1.2         |
|    FakeAndroid     | 6.5.1  |         4.1.3         |

```

github preview:
![image](https://github.com/user-attachments/assets/68d3ebbe-2e1e-43a2-a1c2-64b22ecc7507)

jekyll-commonmark-ghpages preview:

![image](https://github.com/user-attachments/assets/2b5a6976-b590-4f5c-bcba-cd5fc2b03174)

**Comment by jitcor** [comment]
抱歉，原来需要手动开启：
```yaml
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
```
